name: Integration tests

on:
  push:
    branches:
      - "main"
      - "stage"
  pull_request:
    branches:
      - "main"
      - "stage"
      - "monitoring-upgrade-fix-data-races"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run tests
        run: make integration-test
